# Generated by Django 6.0.6 on 2026-06-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveredURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1024, unique=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('last_checked_at', models.DateTimeField(auto_now=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_name', models.CharField(max_length=512)),
                ('scheme_type', models.CharField(choices=[('LOAN', 'Loan'), ('INSURANCE', 'Insurance'), ('SUBSIDY', 'Subsidy'), ('ASSISTANCE', 'Financial Assistance'), ('OTHER', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('eligibility', models.JSONField(help_text='List of eligibility criteria')),
                ('benefits', models.JSONField(help_text='List of financial or material benefits')),
                ('documents_required', models.JSONField(help_text='List of required documents')),
                ('official_url', models.URLField(max_length=1024)),
                ('apply_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('source_hash', models.CharField(help_text='SHA-256 of AI extracted content', max_length=64, unique=True)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
