# Generated by Django 6.0.6 on 2026-06-09 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes_discovery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(blank=True, max_length=512, null=True)),
                ('raw_content', models.TextField(help_text='The raw HTML or raw PDF text')),
                ('clean_content', models.TextField(help_text='The normalized, boilerplate-free text')),
                ('content_hash', models.CharField(help_text='SHA-256 hash of clean_content', max_length=64, unique=True)),
                ('quality_score', models.FloatField(default=0.0, help_text='Heuristic score of relevance')),
                ('is_valid_scheme_page', models.BooleanField(default=False)),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_content', to='schemes_discovery.discoveredurl')),
            ],
        ),
    ]
