# Generated by Django 6.0.6 on 2026-06-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes_discovery', '0002_extractedcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='discoveredurl',
            name='discovery_query',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='discoveredurl',
            name='discovery_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='discoveredurl',
            name='is_relevant',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='discoveredurl',
            name='source_domain',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='discoveredurl',
            name='title',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='discoveredurl',
            name='url',
            field=models.URLField(db_index=True, max_length=1024, unique=True),
        ),
    ]
