# Generated by Django 6.0.6 on 2026-06-09 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes_discovery', '0003_discoveredurl_discovery_query_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='confidence_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='scheme',
            name='extracted_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schemes', to='schemes_discovery.extractedcontent'),
        ),
        migrations.AddField(
            model_name='scheme',
            name='needs_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='official_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
