# Generated by Django 6.0.6 on 2026-06-09 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes_discovery', '0004_scheme_confidence_score_scheme_extracted_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_name', models.CharField(max_length=512, unique=True)),
                ('scheme_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('eligibility', models.JSONField()),
                ('benefits', models.JSONField()),
                ('documents_required', models.JSONField()),
                ('apply_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('current_version', models.CharField(default='v1.0', max_length=10)),
                ('data_quality_score', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(max_length=50)),
                ('details', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('scheme_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schemes_discovery.schememaster')),
            ],
        ),
        migrations.CreateModel(
            name='SchemeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(max_length=10)),
                ('snapshot', models.JSONField(help_text='Full JSON snapshot of the SchemeMaster state')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheme_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='schemes_discovery.schememaster')),
            ],
        ),
        migrations.CreateModel(
            name='SourceMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_type', models.CharField(max_length=50)),
                ('mapped_at', models.DateTimeField(auto_now_add=True)),
                ('extracted_scheme', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='schemes_discovery.scheme')),
                ('scheme_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='schemes_discovery.schememaster')),
            ],
        ),
    ]
