# Generated by Django 6.0.6 on 2026-06-09 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes_discovery', '0005_schememaster_audithistory_schemeversion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, unique=True)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('land_holding_size', models.FloatField(help_text='In hectares')),
                ('farmer_category', models.CharField(max_length=50)),
                ('crop_type', models.JSONField(help_text='List of current crops')),
                ('irrigation_status', models.CharField(max_length=50)),
                ('annual_income', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchemeRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField()),
                ('ai_reasoning', models.TextField()),
                ('matched_conditions', models.JSONField()),
                ('unclear_conditions', models.JSONField()),
                ('is_dismissed', models.BooleanField(default=False)),
                ('is_applied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='schemes_discovery.farmerprofile')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schemes_discovery.schememaster')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_rating', models.IntegerField(choices=[(1, 'Not Relevant'), (2, 'Helpful'), (3, 'Applied')])),
                ('feedback_text', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('recommendation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='schemes_discovery.schemerecommendation')),
            ],
        ),
    ]
