# Generated by Django 6.0.6 on 2026-06-11 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes_discovery', '0006_farmerprofile_schemerecommendation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schememaster',
            name='official_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
